[changelog]
header = "## Changelog\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7) }}]({{ commit.remote.url }}/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
footer = ""
trim = true
