allow_commands = [
  # --- JavaScript / TypeScript
  "^npm (run )?(start|dev|build)",
  "^yarn (run )?(start|dev|build)",
  "^pnpm (run )?(start|dev|build)",
  "^bun (run )?(start|dev|build)",

  # --- Rust
  "^cargo (run|build|publish)",

  # --- Python
  "^poetry (run|build|publish)",
  "^pipenv run",

  # --- Java
  "^mvn (compile|deploy).*",
  "^gradlew? (build|run|publish).*",

  # --- Go
  "^go (build|run|mod tidy)",

  # --- .NET / C#
  "^dotnet (build|run|publish)",

  # --- Database / ORMs
  "prisma (migrate|db|studio)",
]

deny_commands = []

disable_masking = false
