name: Formatting Check
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run rustfmt
        run: cargo fmt -- --check
